spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "This is a secret key!"
  datasource:
    url: jdbc:postgresql://localhost:5433/portfolio_management
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG